"""delete adminuser

Revision ID: 252272eb3a29
Revises: 2bc315240a22
Create Date: 2015-12-17 21:25:12.979437

"""

# revision identifiers, used by Alembic.
revision = '252272eb3a29'
down_revision = '2bc315240a22'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'AdminUser')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'AdminUser',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'uname', mysql.VARCHAR(length=150), nullable=False),
    sa.Column(u'passwd', mysql.VARCHAR(length=150), nullable=False),
    sa.Column(u'regDate', mysql.VARCHAR(length=100), nullable=False),
    sa.Column(u'email', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint(u'id'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
