"""update users

Revision ID: 2bc315240a22
Revises: 381d55919ee3
Create Date: 2015-12-17 21:18:55.423926

"""

# revision identifiers, used by Alembic.
revision = '2bc315240a22'
down_revision = '381d55919ee3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('isAdmin', sa.Boolean(), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'isAdmin')
    ### end Alembic commands ###
