"""create invitecode table

Revision ID: 381d55919ee3
Revises: 5d360c0414e
Create Date: 2015-12-14 21:36:00.753307

"""

# revision identifiers, used by Alembic.
revision = '381d55919ee3'
down_revision = '5d360c0414e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_code_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inviteCode', sa.String(length=50), nullable=False),
    sa.Column('codestatus', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invite_code_list_inviteCode', 'invite_code_list', ['inviteCode'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_invite_code_list_inviteCode', 'invite_code_list')
    op.drop_table('invite_code_list')
    ### end Alembic commands ###
