"""init db

Revision ID: aa9447e0886
Revises: 
Create Date: 2015-11-10 12:30:43.599175

"""

# revision identifiers, used by Alembic.
revision = 'aa9447e0886'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessionID')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessionID',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('data', mysql.VARCHAR(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'MyISAM'
    )
    ### end Alembic commands ###
