"""create admin

Revision ID: b561ad71618
Revises: aa9447e0886
Create Date: 2015-11-10 12:34:15.568775

"""

# revision identifiers, used by Alembic.
revision = 'b561ad71618'
down_revision = 'aa9447e0886'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('AdminUser', sa.Column('test', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('AdminUser', 'test')
    ### end Alembic commands ###
